import type { CardAsset, CardCategory } from './types';

const BASE_ICONS_PATH = '/assets/base-icons';

const createAsset = (category: CardCategory, filename: string): CardAsset => ({
  id: `${category}-${filename.replace('.png', '')}`,
  src: `${BASE_ICONS_PATH}/${category}/${filename}`,
  category,
});

const abstractAssets: CardAsset[] = [
  createAsset('abstract', 'arbus.png'),
  createAsset('abstract', 'base-is-for-everyone.png'),
  createAsset('abstract', 'baseforever.png'),
  createAsset('abstract', 'baserise.png'),
  createAsset('abstract', 'blue-on-base.png'),
  createAsset('abstract', 'coinbidex.png'),
  createAsset('abstract', 'create.png'),
  createAsset('abstract', 'cryptex-finance.png'),
  createAsset('abstract', 'flyte-ai.png'),
  createAsset('abstract', 'foam.png'),
  createAsset('abstract', 'foom.png'),
  createAsset('abstract', 'hyperlane.png'),
  createAsset('abstract', 'hyperware.png'),
  createAsset('abstract', 'incomrwa.png'),
  createAsset('abstract', 'indexy.png'),
  createAsset('abstract', 'legacy-bold.png'),
  createAsset('abstract', 'legend.png'),
  createAsset('abstract', 'libertai.png'),
  createAsset('abstract', 'liquid-mercury.png'),
  createAsset('abstract', 'liquid-staked-eth.png'),
  createAsset('abstract', 'marketvector-digital-assets-25-index.png'),
  createAsset('abstract', 'masq.png'),
  createAsset('abstract', 'masterdex.png'),
  createAsset('abstract', 'moonboots-dao.png'),
  createAsset('abstract', 'morpho-degen.png'),
  createAsset('abstract', 'morpho-eusd.png'),
  createAsset('abstract', 'morpho.png'),
  createAsset('abstract', 'mute-swap-by-virtuals.png'),
  createAsset('abstract', 'mwx-token.png'),
  createAsset('abstract', 'neuy.png'),
  createAsset('abstract', 'paw.png'),
  createAsset('abstract', 'peapods-finance.png'),
  createAsset('abstract', 'perion.png'),
  createAsset('abstract', 'permission-coin.png'),
  createAsset('abstract', 'perps-dao.png'),
  createAsset('abstract', 'pizza.png'),
  createAsset('abstract', 'planet-ix.png'),
  createAsset('abstract', 'play.png'),
  createAsset('abstract', 'resolv-liquidity-provider-token.png'),
  createAsset('abstract', 'retake-tv.png'),
  createAsset('abstract', 'rewardable.png'),
  createAsset('abstract', 'rwa-inc.png'),
  createAsset('abstract', 'smardex.png'),
  createAsset('abstract', 'smart-layer-network.png'),
  createAsset('abstract', 'soon.png'),
  createAsset('abstract', 'sophon.png'),
  createAsset('abstract', 'strawberry-ai.png'),
  createAsset('abstract', 'volatilityx.png'),
];

const coinsAssets: CardAsset[] = [
  createAsset('coins', 'yala-stablecoin.png'),
  createAsset('coins', 'treble.png'),
  createAsset('coins', 'wrapped-backed-coinbase-global.png'),
  createAsset('coins', 'xsgd.png'),
  createAsset('coins', 'theo-short-duration-us-treasury-fund.png'),
  createAsset('coins', 'dinari-cost.png'),
  createAsset('coins', 'franklin-templeton-benji.png'),
  createAsset('coins', 'brazilian-real.png'),
  createAsset('coins', 'forta.png'),
  createAsset('coins', 'wrapped-ampleforth.png'),
  createAsset('coins', 'the-sandbox.png'),
  createAsset('coins', 'botto.png'),
  createAsset('coins', 'xo-protocol.png'),
  createAsset('coins', 'derive.png'),
  createAsset('coins', 'overnight-fi-usdc.png'),
  createAsset('coins', 'dephaser-jpy.png'),
  createAsset('coins', 'wrapped-super-oeth.png'),
  createAsset('coins', 'myeva.png'),
  createAsset('coins', 'web-3-dollar.png'),
  createAsset('coins', 'morpheus-ai.png'),
  createAsset('coins', 'folks.png'),
  createAsset('coins', 'wrapped-bnvda.png'),
  createAsset('coins', 'bold.png'),
  createAsset('coins', 'cryptohub.png'),
  createAsset('coins', 'flex-perpetuals.png'),
  createAsset('coins', 'coin-on-base.png'),
  createAsset('coins', 'wrapped-bmstr.png'),
  createAsset('coins', 'moonwell-flagship-eth-morpho-vault.png'),
  createAsset('coins', 'gains-network.png'),
  createAsset('coins', 'true.png'),
  createAsset('coins', 'tribal.png'),
  createAsset('coins', 'baseswap.png'),
  createAsset('coins', 'fleth.png'),
  createAsset('coins', 'clanker-index.png'),
  createAsset('coins', 'hydrex.png'),
  createAsset('coins', 'gochain.png'),
  createAsset('coins', 'tree.png'),
  createAsset('coins', 'arvos-ai.png'),
  createAsset('coins', 'g-agents-ai.png'),
  createAsset('coins', 'fleek.png'),
  createAsset('coins', 'districts.png'),
  createAsset('coins', 'ether-fi.png'),
  createAsset('coins', 'flayer.png'),
  createAsset('coins', 'etherisc-dip.png'),
  createAsset('coins', 'ethlas.png'),
  createAsset('coins', 'arqx-ai.png'),
  createAsset('coins', 'frax-usd.png'),
  createAsset('coins', 'ethos-reserve-note.png'),
];

const mascotsAssets: CardAsset[] = [
  createAsset('mascots', 'huey.png'),
  createAsset('mascots', 'ricky-the-raccoon.png'),
  createAsset('mascots', 'brian.png'),
  createAsset('mascots', 'boshi.png'),
  createAsset('mascots', 'henlo.png'),
  createAsset('mascots', 'basefrog.png'),
  createAsset('mascots', 'henlo-kart.png'),
  createAsset('mascots', 'young-peezy-aka-pepe.png'),
  createAsset('mascots', 'wrapped-basedoge.png'),
  createAsset('mascots', 'ribbita-by-virtuals.png'),
  createAsset('mascots', 'brett-killer.png'),
  createAsset('mascots', 'based-zlurpee.png'),
  createAsset('mascots', 'based-lambow.png'),
  createAsset('mascots', 'hempy.png'),
  createAsset('mascots', 'based-hoppy.png'),
  createAsset('mascots', 'brett-2-0.png'),
  createAsset('mascots', 'gobl.png'),
  createAsset('mascots', 'gmonchain.png'),
  createAsset('mascots', 'retail-dao.png'),
  createAsset('mascots', 'perpy.png'),
  createAsset('mascots', 'tiny-panda.png'),
  createAsset('mascots', 'tiny-fren.png'),
  createAsset('mascots', 'tickle.png'),
  createAsset('mascots', 'brad.png'),
  createAsset('mascots', 'brat.png'),
  createAsset('mascots', 'frenchie.png'),
  createAsset('mascots', 'pepenguin.png'),
  createAsset('mascots', 'tibo.png'),
  createAsset('mascots', 'sport-bettor-ai.png'),
  createAsset('mascots', 'boysclubbase.png'),
  createAsset('mascots', 'bubu.png'),
  createAsset('mascots', 'cope.png'),
  createAsset('mascots', 'deployer.png'),
  createAsset('mascots', 'pepe-0x69-on-base.png'),
  createAsset('mascots', 'peach-and-pablo.png'),
  createAsset('mascots', 'son-of-brett.png'),
  createAsset('mascots', 'rug-world-assets.png'),
  createAsset('mascots', 'smudge-cat.png'),
  createAsset('mascots', 'corgi.png'),
  createAsset('mascots', 'russell.png'),
  createAsset('mascots', 'riky-the-raccoon.png'),
  createAsset('mascots', 'iaero-protocol-liq.png'),
  createAsset('mascots', 'riku.png'),
  createAsset('mascots', 'monky.png'),
  createAsset('mascots', 'peacepal-ai.png'),
  createAsset('mascots', 'moon.png'),
  createAsset('mascots', 'lordy.png'),
  createAsset('mascots', 'marvin-on-base.png'),
];

const mixedAssets: CardAsset[] = [
  createAsset('mixed', 'jelli.png'),
  createAsset('mixed', 'bracky.png'),
  createAsset('mixed', 'based-usa.png'),
  createAsset('mixed', 'bluepay.png'),
  createAsset('mixed', 'asktianai.png'),
  createAsset('mixed', 'zkrace.png'),
  createAsset('mixed', 'blue-moon.png'),
  createAsset('mixed', 'basic-dog-meme.png'),
  createAsset('mixed', 'basex.png'),
  createAsset('mixed', 'baseprinter.png'),
  createAsset('mixed', 'cortex.png'),
  createAsset('mixed', 'cortensor.png'),
  createAsset('mixed', 'cornucopias.png'),
  createAsset('mixed', 'coinbread.png'),
  createAsset('mixed', 'artto-ai.png'),
  createAsset('mixed', '11am.png'),
  createAsset('mixed', 'yoyo.png'),
  createAsset('mixed', 'wrapped-bmx-liquidity-token.png'),
  createAsset('mixed', 'wewecoin.png'),
  createAsset('mixed', 'volaris-games.png'),
  createAsset('mixed', 'ringfence.png'),
  createAsset('mixed', '1000x-by-virtuals.png'),
  createAsset('mixed', 'braza-by-virtuals.png'),
  createAsset('mixed', 'ethermax.png'),
  createAsset('mixed', 'reservoir-rusd.png'),
  createAsset('mixed', 'hop-protocol.png'),
  createAsset('mixed', 'crazzers-ai.png'),
  createAsset('mixed', 'planet-mojo.png'),
  createAsset('mixed', 'impermax.png'),
  createAsset('mixed', 'javsphere.png'),
  createAsset('mixed', 'pendle.png'),
  createAsset('mixed', 'penjamin-blinkerton.png'),
  createAsset('mixed', 'pkt.png'),
  createAsset('mixed', 'tipn.png'),
  createAsset('mixed', 'monstro-defi.png'),
  createAsset('mixed', 'therapi.png'),
  createAsset('mixed', 'the-nation-token.png'),
  createAsset('mixed', 'spot.png'),
  createAsset('mixed', 'pawthereum.png'),
  createAsset('mixed', 'spiko-us-t-bills-money-market-fund.png'),
  createAsset('mixed', 'sosovalue.png'),
  createAsset('mixed', 'lotry.png'),
  createAsset('mixed', 'smol.png'),
  createAsset('mixed', 'liminal-agent-by-virtuals.png'),
  createAsset('mixed', 'liquid-sonic-drop.png'),
  createAsset('mixed', 'limewire.png'),
  createAsset('mixed', 'striker-league.png'),
  createAsset('mixed', 'mynth.png'),
];

const personsAssets: CardAsset[] = [
  createAsset('persons', 'voice-of-the-gods-by-virtuals.png'),
  createAsset('persons', 'sports-analyst-ai.png'),
  createAsset('persons', 'spira.png'),
  createAsset('persons', 'newton-on-base.png'),
  createAsset('persons', 'lilmiquela-base-eth.png'),
  createAsset('persons', 'lester-by-virtuals.png'),
  createAsset('persons', 'leonardo-ai.png'),
  createAsset('persons', 'jesse.png'),
  createAsset('persons', 'jeffkirdeikis.png'),
  createAsset('persons', 'jeff-ceo.png'),
  createAsset('persons', 'gai16zbrielshai16zpr0.png'),
  createAsset('persons', 'fool.png'),
  createAsset('persons', 'base-god.png'),
  createAsset('persons', 'based-wojak.png'),
  createAsset('persons', 'blue-guy.png'),
  createAsset('persons', 'arcturian-ai-by-virtuals.png'),
  createAsset('persons', 'araistotle.png'),
  createAsset('persons', 'bucci.png'),
  createAsset('persons', '0xmonk-by-virtuals.png'),
  createAsset('persons', 'clanktardio.png'),
  createAsset('persons', 'briun-armstrung.png'),
  createAsset('persons', 'clankermon.png'),
  createAsset('persons', 'crappy-bird-cto.png'),
  createAsset('persons', 'fomo-tocd.png'),
  createAsset('persons', 'crash-on-base.png'),
  createAsset('persons', 'crypticpoet.png'),
  createAsset('persons', 'dessalinesai-by-virtuals.png'),
  createAsset('persons', 'depin-baby.png'),
  createAsset('persons', 'distracted-dudes.png'),
  createAsset('persons', 'cora.png'),
  createAsset('persons', 'cryptoempressx.png'),
  createAsset('persons', 'dyl.png'),
];

const virtualsAssets: CardAsset[] = [
  createAsset('virtuals', 'virtuals_01.png'),
  createAsset('virtuals', 'virtuals_02.png'),
  createAsset('virtuals', 'virtuals_03.png'),
  createAsset('virtuals', 'virtuals_04.png'),
  createAsset('virtuals', 'virtuals_05.png'),
  createAsset('virtuals', 'virtuals_06.png'),
  createAsset('virtuals', 'virtuals_07.png'),
  createAsset('virtuals', 'virtuals_08.png'),
  createAsset('virtuals', 'virtuals_09.png'),
  createAsset('virtuals', 'virtuals_10.png'),
  createAsset('virtuals', 'virtuals_11.png'),
  createAsset('virtuals', 'virtuals_12.png'),
  createAsset('virtuals', 'virtuals_13.png'),
  createAsset('virtuals', 'virtuals_14.png'),
  createAsset('virtuals', 'virtuals_15.png'),
  createAsset('virtuals', 'virtuals_16.png'),
  createAsset('virtuals', 'virtuals_17.png'),
  createAsset('virtuals', 'virtuals_18.png'),
  createAsset('virtuals', 'virtuals_19.png'),
  createAsset('virtuals', 'virtuals_20.png'),
  createAsset('virtuals', 'virtuals_21.png'),
  createAsset('virtuals', 'virtuals_22.png'),
  createAsset('virtuals', 'virtuals_23.png'),
  createAsset('virtuals', 'virtuals_24.png'),
  createAsset('virtuals', 'virtuals_25.png'),
  createAsset('virtuals', 'virtuals_26.png'),
  createAsset('virtuals', 'virtuals_27.png'),
  createAsset('virtuals', 'virtuals_28.png'),
  createAsset('virtuals', 'virtuals_29.png'),
  createAsset('virtuals', 'virtuals_30.png'),
  createAsset('virtuals', 'virtuals_31.png'),
  createAsset('virtuals', 'virtuals_32.png'),
  createAsset('virtuals', 'virtuals_33.png'),
  createAsset('virtuals', 'virtuals_34.png'),
  createAsset('virtuals', 'virtuals_35.png'),
  createAsset('virtuals', 'virtuals_36.png'),
  createAsset('virtuals', 'virtuals_37.png'),
  createAsset('virtuals', 'virtuals_38.png'),
  createAsset('virtuals', 'virtuals_39.png'),
  createAsset('virtuals', 'virtuals_40.png'),
  createAsset('virtuals', 'virtuals_41.png'),
  createAsset('virtuals', 'virtuals_42.png'),
  createAsset('virtuals', 'virtuals_43.png'),
  createAsset('virtuals', 'virtuals_44.png'),
  createAsset('virtuals', 'virtuals_45.png'),
  createAsset('virtuals', 'virtuals_46.png'),
  createAsset('virtuals', 'virtuals_47.png'),
  createAsset('virtuals', 'virtuals_48.png'),
];

const ASSETS_BY_CATEGORY: Record<CardCategory, CardAsset[]> = {
  abstract: abstractAssets,
  coins: coinsAssets,
  mascots: mascotsAssets,
  mixed: mixedAssets,
  persons: personsAssets,
  virtuals: virtualsAssets,
};

export const ALL_ASSETS: CardAsset[] = Object.values(ASSETS_BY_CATEGORY).flat();

export function getAssetsByCategory(category: CardCategory): CardAsset[] {
  return [...ASSETS_BY_CATEGORY[category]];
}

export function getAllAssets(): CardAsset[] {
  return [...ALL_ASSETS];
}

export function getAssetsByCategories(categories: CardCategory[]): CardAsset[] {
  const uniqueCategories = [...new Set(categories)];
  return uniqueCategories.flatMap((category) => getAssetsByCategory(category));
}
